ViewComponents/RandevuListViewComponent.cs
using Güzellik_Merkezi.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Güzellik_Merkezi.ViewComponents
{
    public class RandevuListViewComponent:ViewComponent
    {
        private readonly IRandevuService _randevuService;
        public RandevuListViewComponent(IRandevuService randevuService)
        {
            _randevuService = randevuService;
        }

        public IViewComponentResult Invoke()
        {
            var randevu = _randevuService.GetAll();
            return View(randevu);
        }
    }
}

Views/Admin/CreateMüsteri.cshtml
@model Güzellik_Merkezi.Models.AppUser
@{
    Layout = "_LayoutAdmin";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Yeni Müşteri</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</head>
<body>

    <h4>Müşteri</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-controller="Admin" asp-action="CreateMüşteri">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Ad" class="control-label"></label>
                    <input asp-for="Ad" class="form-control" />
                    <span asp-validation-for="Ad" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Soyad" class="control-label"></label>
                    <input asp-for="Soyad" class="form-control" />
                    <span asp-validation-for="Soyad" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PhoneNumber" class="control-label"></label>
                    <input asp-for="PhoneNumber" class="form-control" />
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" asp-controller="Admin" asp-action="CreateMüsteri" value="Kaydet" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Geri Dön</a>
    </div>

  
</body>
</html>

Views/Admin/CreateRandevu.cshtml
@model KuaförRandevu00.Models.Randevu

@{
    Layout = "_LayoutAdmin";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Yeni Randevu</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</head>
<body>

    <h4>Randevu</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-controller="Admin" asp-action="CreateRandevu">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Start" class="control-label">Tarih</label>
                    <input asp-for="Start" class="form-control" />
                    <span asp-validation-for="Start" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Text" class="control-label">Alinacak Hizmet</label>
                    <input asp-for="Text" class="form-control" />
                    <span asp-validation-for="Text" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Ad" class="control-label"></label>
                    <input asp-for="Ad" class="form-control" />
                    <span asp-validation-for="Ad" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Soyad" class="control-label"></label>
                    <input asp-for="Soyad" class="form-control" />
                    <span asp-validation-for="Soyad" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Telno" class="control-label"></label>
                    <input asp-for="Telno" class="form-control" />
                    <span asp-validation-for="Telno" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" asp-controller="Admin" asp-action="CreateRandevu" value="Kaydet" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Geri Dön</a>
    </div>

   
</body>
</html>

Views/Admin/DeleteMüsteri.cshtml
@model Güzellik_Merkezi.Models.AppUser

@{
    Layout = "_LayoutAdmin";
}


<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<h3>Müşteri Silinecek Emin Misiniz?</h3>
<div>

    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ad)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ad)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Soyad)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Soyad)
        </dd>

    </dl>
    


    <form asp-action="DeleteMüsteri">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Sil" class="btn btn-danger" /> |
        <a asp-action="Index">Geri Dön</a>
    </form>
</div>

Views/Admin/DeleteRandevu.cshtml
@model KuaförRandevu00.Models.Randevu

@{
    Layout = "_LayoutAdmin";
}


<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<h3>Randevu silinecek Emin Misiniz?</h3>
<div>

    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Tarih
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Start)
        </dd>
        <dt class="col-sm-2">
            Alınacak Hizmet/Aciklama
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ad)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ad)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Soyad)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Soyad)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Telno)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Telno)
        </dd>
    </dl>

    <form asp-action="DeleteRandevu">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Sil" class="btn btn-danger" /> |
        <a asp-action="Index">Geri Dön</a>
    </form>
</div>

Views/Admin/Edit.cshtml
@model Güzellik_Merkezi.Models.AppRole

@{ 
    Layout = "_LayoutAdmin";
}
<h4>Admin Bilgilerini Güncelle</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label">Kullanıcı Adı</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sifre" class="control-label"></label>
                <input asp-for="Sifre" class="form-control" />
                <span asp-validation-for="Sifre" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="Kaydet" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Geri Dön</a>
</div>

Views/Admin/EditMüsteri.cshtml
@model Güzellik_Merkezi.Models.AppUser

@{
    Layout = "_LayoutAdmin";
}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<h4>Müşteri</h4>
<hr />
@ViewBag.mes
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Admin" asp-action="EditMüsteri">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Ad" class="control-label"></label>
                <input asp-for="Ad" class="form-control" />
                <span asp-validation-for="Ad" class="text-danger"></span>

            </div>
            <div class="form-group">
                <label asp-for="Soyad" class="control-label"></label>
                <input asp-for="Soyad" class="form-control" />
                <span asp-validation-for="Soyad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label">Telno</label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Kaydet" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Geri Dön</a>
</div>

Views/Admin/EditRandevu.cshtml
@model KuaförRandevu00.Models.Randevu

@{
    Layout = "_LayoutAdmin";
}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<h4>Randevu</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditRandevu">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Start" class="control-label"></label>
                <input asp-for="Start" class="form-control" />
                <span asp-validation-for="Start" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ad" class="control-label"></label>
                <input asp-for="Ad" class="form-control" />
                <span asp-validation-for="Ad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Soyad" class="control-label"></label>
                <input asp-for="Soyad" class="form-control" />
                <span asp-validation-for="Soyad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telno" class="control-label"></label>
                <input asp-for="Telno" class="form-control" />
                <span asp-validation-for="Telno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Kaydet" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Geri Dön</a>
</div>

Views/Admin/Index.cshtml
@{
    Layout = "_LayoutAdmin";
}

<b> @ViewBag.msj0</b>

@await Component.InvokeAsync("RandevuList")
@*<h1>Admin Sayfası</h1>*@

Views/Admin/MüsteriIndex.cshtml
@{
    Layout = "_LayoutAdmin";
}


@await Component.InvokeAsync("MüsterilerList")