Controllers/ServisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KuaförRandevu00.Models;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Güzellik_Merkezi.Data;
using Microsoft.AspNetCore.Authorization;

namespace KuaförRandevu00.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ServisController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;

        public ServisController(ApplicationDbContext context,IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
        }

        // GET: Servis
        public async Task<IActionResult> Index()
        {
            return View(await _context.Servislers.ToListAsync());
        }

        // GET: Servis/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var servis = await _context.Servislers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (servis == null)
            {
                return NotFound();
            }

            return View(servis);
        }

        // GET: Servis/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Servis/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,LogoYazısı,Baslik,Aciklama,Baslik1,Aciklama1,Baslik2,Aciklama2,Baslik3,Aciklama3,Baslik4,Aciklama4,Baslik5,Aciklama5,Baslik6,Aciklama6,ClientSaysbaslik,ClientSaysAciklama,ResimDosyası,Müsteriisim,MüsteriAciklama,ResimDosyası2,Müsteriisim2,MüsteriAciklama2,ResimDosyası3,Müsteriisim3,MüsteriAciklama3,KalitelisacBaslik,KalitelisacAciklama,ResimDosyası1")] Servis servis)
        {

            if (ModelState.IsValid)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                string wwwRootPaht1 = _hostEnvironment.WebRootPath;
                string wwwRootPath2 = _hostEnvironment.WebRootPath;
                string wwwRootPaht3 = _hostEnvironment.WebRootPath;

                string fileName = Path.GetFileNameWithoutExtension(servis.ResimDosyası.FileName);
                string fileName1 = Path.GetFileNameWithoutExtension(servis.ResimDosyası1.FileName);
                string fileName2 = Path.GetFileNameWithoutExtension(servis.ResimDosyası2.FileName);
                string fileName3 = Path.GetFileNameWithoutExtension(servis.ResimDosyası3.FileName);

                string extension = Path.GetExtension(servis.ResimDosyası.FileName);
                string extension1 = Path.GetExtension(servis.ResimDosyası1.FileName);
                string extension2 = Path.GetExtension(servis.ResimDosyası2.FileName);
                string extension3 = Path.GetExtension(servis.ResimDosyası3.FileName);


                servis.ResimYolu= fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                servis.ResimYolu1 = fileName1 = fileName1 + DateTime.Now.ToString("yymmssfff") + extension;
                servis.ResimYolu2 = fileName2 = fileName2 + DateTime.Now.ToString("yymmssfff") + extension;
                servis.ResimYolu3 = fileName3 = fileName3 + DateTime.Now.ToString("yymmssfff") + extension;

                string path = Path.Combine(wwwRootPath + "/ServislerimizResimleri/", fileName);
                string path1 = Path.Combine(wwwRootPaht1 + "/ServislerimizResimleri/", fileName1);
                string path2 = Path.Combine(wwwRootPath2 + "/ServislerimizResimleri/", fileName2);
                string path3 = Path.Combine(wwwRootPaht3 + "/ServislerimizResimleri/", fileName3);

                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await servis.ResimDosyası.CopyToAsync(fileStream);
                }

                using (var fileStream1 = new FileStream(path1,FileMode.Create))
                {
                    await servis.ResimDosyası1.CopyToAsync(fileStream1);
                }
                using (var fileStream2 = new FileStream(path2, FileMode.Create))
                {
                    await servis.ResimDosyası2.CopyToAsync(fileStream2);
                }
                using (var fileStream3 = new FileStream(path3, FileMode.Create))
                {
                    await servis.ResimDosyası3.CopyToAsync(fileStream3);
                }

                _context.Add(servis);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(servis);
        }

        // GET: Servis/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var servis = await _context.Servislers.FindAsync(id);
            if (servis == null)
            {
                return NotFound();
            }
            return View(servis);
        }

        // POST: Servis/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,LogoYazısı,Baslik,Aciklama,Baslik1,Aciklama1,Baslik2,Aciklama2,Baslik3,Aciklama3,Baslik4,Aciklama4,Baslik5,Aciklama5,Baslik6,Aciklama6,ClientSaysbaslik,ClientSaysAciklama,ResimYolu,Müsteriisim,MüsteriAciklama,ResimYolu2,Müsteriisim2,MüsteriAciklama2,ResimYolu3,Müsteriisim3,MüsteriAciklama3,KalitelisacBaslik,KalitelisacAciklama,ResimYolu1")] Servis servis)
        {
            if (id != servis.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(servis);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ServisExists(servis.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(servis);
        }

        // GET: Servis/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var servis = await _context.Servislers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (servis == null)
            {
                return NotFound();
            }

            return View(servis);
        }

        // POST: Servis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

            var servis = await _context.Servislers.FindAsync(id);
            var servis1 = await _context.Servislers.FindAsync(id);
            var servis2 = await _context.Servislers.FindAsync(id);
            var servis3 = await _context.Servislers.FindAsync(id);

            var imagePath = Path.Combine(_hostEnvironment.WebRootPath, "ServislerimizResimleri", servis.ResimYolu);
            var imagePath1 = Path.Combine(_hostEnvironment.WebRootPath, "ServislerimizResimleri", servis.ResimYolu1);
            var imagePath2 = Path.Combine(_hostEnvironment.WebRootPath, "ServislerimizResimleri", servis.ResimYolu2);
            var imagePath3 = Path.Combine(_hostEnvironment.WebRootPath, "ServislerimizResimleri", servis.ResimYolu3);

            if (System.IO.File.Exists(imagePath))
            {
                System.IO.File.Delete(imagePath);
                System.IO.File.Delete(imagePath1);
                System.IO.File.Delete(imagePath2);
                System.IO.File.Delete(imagePath3);
            }


            _context.Servislers.Remove(servis);
            _context.Servislers.Remove(servis1);
            _context.Servislers.Remove(servis2);
            _context.Servislers.Remove(servis3);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ServisExists(int id)
        {
            return _context.Servislers.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> USerManager


  

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Güzellik_Merkezi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site2.css" />
</head>
<body>
    <header>




        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                @if (SignInManager.IsSignedIn(User))
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>}
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">




                        @if (User.IsInRole("Admin"))
                        {
                            <a class="btn btn btn-outline-danger btn-sm ml-3" asp-area="" asp-controller="Admin" asp-action="Index"><i class="icon-fast-backward fa-user"></i>Admin Sayfasına Git</a>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Güzellik_Merkezi - <a asp-area="" asp-controller="Home" asp-action="Index">Başa Dön</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site2.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout1.cshtml
@model IEnumerable<KuaförRandevu00.Models.HomePage>
@{ Layout = null;}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KuaförRandevu</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <link href="~/css/Takvim.css" rel="stylesheet" />
    <!------ Include the above in your HEAD tag ---------->

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

</head>





@foreach (var item in Model.TakeLast(1))
{



    <header class="site-navbar site-navbar-target" role="banner">

        <div class="container">
            <div class="row align-items-center position-relative">

                <div class="col-3 ">
                    <div class="site-logo">
                        <a asp-controller="HomeController1" asp-action="Index">@item.LogoYazısı</a>
                    </div>
                </div>

                <div class="col-9  text-right">


                    <span class="d-inline-block d-lg-none"><a href="#" class="text-white site-menu-toggle js-menu-toggle py-5 text-white"><span class="icon-menu h3 text-white"></span></a></span>



                    <nav class="site-navigation text-right ml-auto d-none d-lg-block" role="navigation">
                        <ul class="site-menu main-menu js-clone-nav ml-auto ">
                            <li class="active"><a asp-controller="HomeController1" asp-action="Index" class="nav-link">Anasayfa</a></li>
                            <li><a asp-controller="HomeController1" asp-action="Hizmetler" class="nav-link">Hizmetler</a></li>
                            <li><a asp-controller="HomeController1" asp-action="İletisim" class="nav-link">İletişim</a></li>
                            <li><a href="contact.html" class="nav-link"></a></li>
                        </ul>
                    </nav>
                </div>


            </div>
        </div>

    </header>

}

<div>
    @RenderBody()
</div>

@foreach (var item in Model.TakeLast(1))
{


    <footer class="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <img src="@("~/HomePageResimleri/"+item.ResimYolu4)" class="img-fluid" alt="Image" asp-append-version="true">
                    <h2 class="footer-heading mb-3">Hakkımızda</h2>
                    <p>@item.AciklamaKaliteliSacKesimi</p>
                </div>
                <div class="col-lg-8 ml-auto">
                    <div class="row">
                        <div class="col-lg-6 ml-auto">
                            <h2 class="footer-heading mb-4">Quick Links</h2>
                            <ul class="list-unstyled">
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Testimonials</a></li>
                                <li><a href="#">Terms of Service</a></li>
                                <li><a href="#">Privacy</a></li>
                                <li><a href="#">Contact Us</a></li>
                            </ul>
                        </div>
                        <div class="col-lg-6">
                            <h2 class="footer-heading mb-4">Newsletter</h2>
                            <form action="#" class="d-flex" class="subscribe">
                                <input type="text" class="form-control mr-3" placeholder="Email">
                                <input type="submit" value="Send" class="btn btn-primary">
                            </form>
                        </div>

                    </div>
                </div>
            </div>
            <div class="row pt-5 mt-5 text-center">
                <div class="col-md-12">
                    <div class="border-top pt-5">
                        <p>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;
                            <script>(new Date().getFullYear());</script> @*All rights reserved | This template is made with*@ <i class="icon-heart text-danger" aria-hidden="true"></i> İbrahim Ayfer <a target="_blank"></a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>

            </div>
        </div>
    </footer>

}
</html>

Views/Shared/_LayoutAdmin.cshtml
@{ Layout = null; }
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>Admin Sayfası</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/dashboard/">

    <!-- Bootstrap core CSS -->
    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @*@media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }*@
    </style>
    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" asp-controller="Admin" asp-action="Index">Admin Panel</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
        <ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
                <a class="nav-link" asp-controller="Home" asp-action="Index">Çıkış Yap</a>
            </li>
        </ul>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="sidebar-sticky pt-3">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" asp-controller="Admin" asp-action="Index">
                                <span data-feather="calendar"></span>
                                Randevular<span class="sr-only">(current)</span>
                            </a>

                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Admin" asp-action="MüsteriIndex">
                                <span data-feather="users"></span>
                                Müşteriler
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="HomePage" asp-action="Index">
                                <span data-feather="file-text"></span>
                                Homepage Sayfası
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Hizmetler" asp-action="Index">
                                <span data-feather="calendar"></span>
                                Hizmetler ve Fiyat Sayfası
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Servis" asp-action="Index">
                                <span data-feather="globe"></span>
                                Hizmetlerimiz Sayfası
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="İletisim" asp-action="Index">
                                <span data-feather="layers"></span>
                                İletişim Sayfası
                            </a>
                        </li>

                        @*<li class="nav-item">
                            <a class="nav-link" asp-controller="Admin" asp-action="Edit">
                                <span data-feather="lock"></span>
                                Admin Bilgileri
                            </a>
                        </li>*@

                    </ul>

                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>Saved reports</span>
                        <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
                            <span data-feather="plus-circle"></span>
                        </a>
                    </h6>
                    <ul class="nav flex-column mb-2">
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Current month
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Last quarter
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Social engagement
                            </a>
                        </li>
                    </ul>

                </div>
            </nav>


            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                    <h1 class="h2"></h1>
                    <div class="btn-toolbar mb-2 mb-md-0">
                        <div class="btn-group mr-2">
                            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
                            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
                        </div>
                        <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
                            <span data-feather="calendar"></span>
                            This week
                        </button>
                    </div>
                </div>

                <div>
                    <main role="main" class="pb-3">

                        @RenderBody()
                    </main>
                </div>



                @*<canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>*@


            </main>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
    <script src="~/AdminPanel/dashboard.js"></script>
</body>
</html>

Views/Shared/_LayoutServis.cshtml
@model IEnumerable<KuaförRandevu00.Models.Servis>
@{ 
    Layout = null;
}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KuaförRandevu</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

@foreach (var item in Model.TakeLast(1))
{




        <header class="site-navbar site-navbar-target" role="banner">

            <div class="container">
                <div class="row align-items-center position-relative">

                    <div class="col-3 ">
                        <div class="site-logo">
                            <a asp-controller="HomeController1" asp-action="Index">@item.LogoYazısı</a>
                        </div>
                    </div>

                    <div class="col-9  text-right">


                        <span class="d-inline-block d-lg-none"><a href="#" class="text-white site-menu-toggle js-menu-toggle py-5 text-white"><span class="icon-menu h3 text-white"></span></a></span>



                        <nav class="site-navigation text-right ml-auto d-none d-lg-block" role="navigation">
                            <ul class="site-menu main-menu js-clone-nav ml-auto ">
                                <li><a asp-controller="HomeController1" asp-action="Index" class="nav-link">Anasayfa</a></li>
                                <li class="active"><a asp-controller="HomeController1" asp-action="Index" class="nav-link">Hizmetler</a></li>
                                <li><a asp-controller="HomeController1" asp-action="İletisim" class="nav-link">İletişim</a></li>
                            </ul>
                        </nav>
                    </div>


                </div>
            </div>

        </header>

}
        
 <div>
        @RenderBody()
    </div>


@foreach (var item in Model.TakeLast(1))
{



        <footer class="site-footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3">
                        <img src="@("~/ServislerimizResimleri/"+item.ResimYolu1)" alt="Image" class="img-fluid mb-5" asp-append-version="true">
                        <h2 class="footer-heading mb-3">About Us</h2>
                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. </p>
                    </div>
                    <div class="col-lg-8 ml-auto">
                        <div class="row">
                            <div class="col-lg-6 ml-auto">
                                <h2 class="footer-heading mb-4">Quick Links</h2>
                                <ul class="list-unstyled">
                                    <li><a href="#">About Us</a></li>
                                    <li><a href="#">Testimonials</a></li>
                                    <li><a href="#">Terms of Service</a></li>
                                    <li><a href="#">Privacy</a></li>
                                    <li><a href="#">Contact Us</a></li>
                                </ul>
                            </div>
                            <div class="col-lg-6">
                                <h2 class="footer-heading mb-4">Newsletter</h2>
                                <form action="#" class="d-flex" class="subscribe">
                                    <input type="text" class="form-control mr-3" placeholder="Email">
                                    <input type="submit" value="Send" class="btn btn-primary">
                                </form>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="row pt-5 mt-5 text-center">
                    <div class="col-md-12">
                        <div class="border-top pt-5">
                            <p>
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                Copyright &copy;
                                <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            </p>
                        </div>
                    </div>

                </div>
            </div>
        </footer>
}
</html>