Models/Hizmetler.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace KuaförRandevu00.Models
{
    public class Hizmetler
    {

        public int Id { get; set; }

      

        [Column(TypeName = "nvarchar(100)")]
        [DisplayName("Image Name")]
        public string ResimYolu { get; set; }


        [NotMapped]
        [DisplayName("Upload File")]
        public IFormFile ResimDosyası { get; set; }

        public string Baslik { get; set; }

        public string Hizmet { get; set; }
        public string Hizmet1 { get; set; }
        public string Hizmet2 { get; set; }
        public string Hizmet3 { get; set; }
        public string Hizmet4 { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal? Fiyat { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal? Fiyat1 { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal? Fiyat2 { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal? Fiyat3 { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal? Fiyat4 { get; set; }


    }
}

Models/İletisim.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace KuaförRandevu00.Models
{
    public class İletisim
    {
        [Key]
        public int Id { get; set; }
        public string LogoYazısı { get; set; }
        public string Baslik { get; set; }
        public string Aciklama { get; set; }
        public string Baslik1{ get; set; }
        public string Aciklama1 { get; set; }
        public string Adres { get; set; }
        public string TelNo { get; set; }
        public string EPosta { get; set; }
    }
}

Controllers/HizmetlerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KuaförRandevu00.Models;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Güzellik_Merkezi.Data;
using Microsoft.AspNetCore.Authorization;

namespace KuaförRandevu00.Controllers
{
    [Authorize(Roles = "Admin")]
    public class HizmetlerController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;
        public HizmetlerController(ApplicationDbContext context,IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
        }

        // GET: Hizmetler
        public async Task<IActionResult> Index()
        {
            return View(await _context.Hizmetlers.ToListAsync());
        }



        // GET: Hizmetler/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hizmetler = await _context.Hizmetlers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (hizmetler == null)
            {
                return NotFound();
            }

            return View(hizmetler);
        }

        // GET: Hizmetler/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Hizmetler/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,BaslikServisler,BaslikAciklama,ResimDosyası,Baslik,Hizmet,Hizmet1,Hizmet2,Hizmet3,Hizmet4,Fiyat,Fiyat1,Fiyat2,Fiyat3,Fiyat4")] Hizmetler hizmetler)
        {
            if (ModelState.IsValid)
            {
                string wwwRoothPath = _hostEnvironment.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(hizmetler.ResimDosyası.FileName);
                string extension = Path.GetExtension(hizmetler.ResimDosyası.FileName);
                hizmetler.ResimYolu = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                string path = Path.Combine(wwwRoothPath + "/HizmetlerResimleri/", fileName);

                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await hizmetler.ResimDosyası.CopyToAsync(fileStream);
                }


                _context.Add(hizmetler);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(hizmetler);
        }

        // GET: Hizmetler/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hizmetler = await _context.Hizmetlers.FindAsync(id);
            if (hizmetler == null)
            {
                return NotFound();
            }
            return View(hizmetler);
        }

        // POST: Hizmetler/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,BaslikServisler,BaslikAciklama,ResimYolu,Baslik,Hizmet,Hizmet1,Hizmet2,Hizmet3,Hizmet4,Fiyat,Fiyat1,Fiyat2,Fiyat3,Fiyat4")] Hizmetler hizmetler)
        {
            if (id != hizmetler.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hizmetler);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HizmetlerExists(hizmetler.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(hizmetler);
        }

        // GET: Hizmetler/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hizmetler = await _context.Hizmetlers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (hizmetler == null)
            {
                return NotFound();
            }

            return View(hizmetler);
        }

        // POST: Hizmetler/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

            var hizmetler = await _context.Hizmetlers.FindAsync(id);
            var imagePath = Path.Combine(_hostEnvironment.WebRootPath, "HizmetlerResimleri", hizmetler.ResimYolu);

            if (System.IO.File.Exists(imagePath))
            {
                System.IO.File.Delete(imagePath);
            }
            _context.Hizmetlers.Remove(hizmetler);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HizmetlerExists(int id)
        {
            return _context.Hizmetlers.Any(e => e.Id == id);
        }
    }
}

Controllers/İletisimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KuaförRandevu00.Models;
using Güzellik_Merkezi.Data;
using Microsoft.AspNetCore.Authorization;

namespace KuaförRandevu00.Controllers
{
    [Authorize(Roles = "Admin")]
    public class İletisimController : Controller
    {
        private readonly ApplicationDbContext _context;

        public İletisimController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: İletisim
        public async Task<IActionResult> Index()
        {
            return View(await _context.İletisims.ToListAsync());
        }

        // GET: İletisim/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var İletisim = await _context.İletisims
                .FirstOrDefaultAsync(m => m.Id == id);
            if (İletisim == null)
            {
                return NotFound();
            }

            return View(İletisim);
        }

        // GET: İletisim/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: İletisim/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,LogoYazısı,Baslik,Aciklama,Baslik1,Aciklama1,Adres,TelNo,EPosta")] İletisim İletisim)
        {
            if (ModelState.IsValid)
            {
                _context.Add(İletisim);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(İletisim);
        }



        // GET: İletisim/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var İletisim = await _context.İletisims.FindAsync(id);
            if (İletisim == null)
            {
                return NotFound();
            }
            return View(İletisim);
        }

        // POST: İletisim/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,LogoYazısı,Baslik,Aciklama,Baslik1,Aciklama1,Adres,TelNo,EPosta")] İletisim İletisim)
        {
            if (id != İletisim.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(İletisim);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!İletisimExists(İletisim.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(İletisim);
        }

        // GET: İletisim/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var İletisim = await _context.İletisims
                .FirstOrDefaultAsync(m => m.Id == id);
            if (İletisim == null)
            {
                return NotFound();
            }

            return View(İletisim);
        }

        // POST: İletisim/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var İletisim = await _context.İletisims.FindAsync(id);
            _context.İletisims.Remove(İletisim);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool İletisimExists(int id)
        {
            return _context.İletisims.Any(e => e.Id == id);
        }
    }
}

ViewComponents/HizmetlerListViewComponent.cs
using KuaförRandevu00.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KuaförRandevu00.ViewComponents
{
    public class HizmetlerListViewComponent : ViewComponent
    {
        private readonly IHizmetService _hizmetService;

        public HizmetlerListViewComponent(IHizmetService hizmetService)
        {
            _hizmetService = hizmetService;
        }


        public IViewComponentResult Invoke()
        {

            var hizmet=  _hizmetService.GetAll();
            return View(hizmet);
        }
    }
}

Views/HomeController1/Index.cshtml
@model IEnumerable<KuaförRandevu00.Models.HomePage>
@{ Layout = "_Layout1"; }

<!doctype html>
<html lang="en">

<head>
    <title>Barberz</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=DM+Sans:300,400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="~/barberz/barberz/fonts/icomoon/style.css">
    <link rel="stylesheet" href="~/barberz/barberz/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/barberz/barberz/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="~/barberz/barberz/css/jquery.fancybox.min.css">
    <link rel="stylesheet" href="~/barberz/barberz/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/barberz/barberz/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/barberz/barberz/fonts/flaticon/font/flaticon.css">
    <link rel="stylesheet" href="~/barberz/barberz/css/aos.css">
    <link href="C:\Users\Lenova\.nuget\packages\bootstrap\4.5.3\contentFiles\any\any\wwwroot\css\bootstrap.min.css" rel="stylesheet" />
    <link href="C:\Users\Lenova\.nuget\packages\bootstrap\4.5.3\contentFiles\any\any\wwwroot\css\bootstrap-reboot.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-reboot.css" rel="stylesheet" />

    <!-- MAIN CSS -->



    <link rel="stylesheet" href="~/barberz/barberz/css/style.css">

</head>

<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">


    <div class="site-wrap" id="home-section">

        <div class="site-mobile-menu site-navbar-target">
            <div class="site-mobile-menu-header">
                <div class="site-mobile-menu-close mt-3">
                    <span class="icon-close2 js-menu-toggle"></span>
                </div>
            </div>
            <div class="site-mobile-menu-body"></div>
        </div>
        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">

            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Randevu Alabilmek İçin Üye Olunuz</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                    <div class="modal-footer">
                        <a asp-area="Identity" asp-page="/Account/Login"><button type="button" class="btn btn-info">GirisYap</button></a>
                        <a asp-area="Identity" asp-page="/Account/Register"><button type="button" class="btn btn-primary">Hızlı Üye</button></a>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapat</button>
                    </div>
                </div>
            </div>
        </div>

        @foreach (var item in Model.TakeLast(1))
        {



<div class="ftco-blocks-cover-1">
    <div class="site-section-cover overlay" data-stellar-background-ratio="0.5" style="background-image: url('/barberz/barberz/images/hero_1.jpg') ">
        <div class="container">
            <div class="row align-items-center justify-content-center text-center">
                <div class="col-md-7">
                    <h1 class="mb-3">@item.Baslik </h1>
                    <p>@item.Aciklama</p>
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                        Randevu Al
                    </button>

                </div>
            </div>
        </div>
    </div>
</div>


                <div class="site-section">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-6 mb-5 mb-lg-0">
                                <div class="img-years">
                                    <img src="@("~/HomePageResimleri/"+item.ResimYolu)" class="img-fluid" alt="Image" asp-append-version="true">

                                    <div class="year">
                                        <span>3 <span>years in <br>excellent service</span></span>
                                    </div>
                                </div>

                            </div>
                            <div class="col-lg-5 ml-auto pl-lg-5 text-center">
                                <h3 class="scissors text-center">@item.Baslik1</h3>
                                <p class="mb-5 lead">@item.Aciklama1</p>
                                <p><a href="#" class="btn btn-primary">Learn More</a></p>
                            </div>
                        </div>
                    </div>
                </div>

                                <h3 class="scissors text-center">
                                    @item.BaslikServisler
                                </h3>
                                                <p class="mb-5 lead">
                                                    @item.BaslikAciklama
                                                </p>





                                                                <div class="site-section bg-light">
                                                                    <div class="container">
                                                                        <div class="row justify-content-center mb-5">
                                                                            <div class="col-md-7 text-center">
                                                                                <h3 class="scissors text-center">@item.ServislerBasli</h3>
                                                                                <p class="mb-5 lead">@item.SrvislerAciklama</p>
                                                                            </div>
                                                                        </div>
                                                                        @await Component.InvokeAsync("HizmetlerList")

                                                                        <h3 class="scissors text-center">@item.BaslikDigerSacStilleri</h3>
                                                                        <p class="mb-5 lead">@item.AciklamaDigerSacStilleri</p>
                                                                        <div class="row hair-style">
                                                                            <div class="col-lg-4 col-md-4 col-sm-6 col-12">
                                                                                <a href="#" class="place">
                                                                                    <img src="@("~/HomePageResimleri/"+item.ResimYolu1)" class="img-fluid" alt="Image" asp-append-version="true">

                                                                                    @*<span>$50.00 only</span>*@
                                                                                </a>
                                                                            </div>
                                                                            <div class="col-lg-4 col-md-4 col-sm-6 col-12">
                                                                                <a href="#" class="place">
                                                                                    <img src="@("~/HomePageResimleri/"+item.ResimYolu2)" class="img-fluid" alt="Image" asp-append-version="true">

                                                                                    @*<span>$50.00 only</span>*@
                                                                                </a>
                                                                            </div>
                                                                            <div class="col-lg-4 col-md-4 col-sm-6 col-12">
                                                                                <a href="#" class="place">
                                                                                    <img src="@("~/HomePageResimleri/"+item.ResimYolu3)" class="img-fluid" alt="Image" asp-append-version="true">
                                                                                    <h2>@item.BaslikKaliteliSacKesimi</h2>
                                                                                    @*<span>$50.00 only</span>*@
                                                                                </a>
                                                                            </div>

                                                                        </div>
                                                                    </div>
                                                                </div> <!-- END section -->}




        <div class="site-section section-3" data-stellar-background-ratio="0.5" style="background-image: url('/barberz/barberz/images/hero_1.jpg');">
            <div class="container">
                <div class="row justify-content-center text-center">
                    <div class="col-7 text-center mb-5">
                        <h2 class="text-white scissors primary-color-icon text-center">Quality Haircut</h2>
                        <p class="lead text-white mb-5">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laboriosam quo doloribus, suscipit libero, voluptate aliquam.</p>
                        <p><a href="#" class="btn btn-primary">Contact Us Now</a></p>
                    </div>
                </div>
            </div>
        </div>





    </div>

    <script src="~/barberz/barberz/js/jquery-3.3.1.min.js"></script>
    <script src="~/barberz/barberz/js/jquery-migrate-3.0.0.js"></script>
    <script src="~/barberz/barberz/js/popper.min.js"></script>
    <script src="~/barberz/barberz/js/bootstrap.min.js"></script>
    <script src="~/barberz/barberz/js/owl.carousel.min.js"></script>
    <script src="~/barberz/barberz/js/jquery.sticky.js"></script>
    <script src="~/barberz/barberz/js/jquery.waypoints.min.js"></script>
    <script src="~/barberz/barberz/js/jquery.animateNumber.min.js"></script>
    <script src="~/barberz/barberz/js/jquery.fancybox.min.js"></script>
    <script src="~/barberz/barberz/js/jquery.stellar.min.js"></script>
    <script src="~/barberz/barberz/js/jquery.easing.1.3.js"></script>
    <script src="~/barberz/barberz/js/bootstrap-datepicker.min.js"></script>
    <script src="~/barberz/barberz/js/aos.js"></script>

    <script src="~/barberz/barberz/js/main.js"></script>
    <script src="C:\Users\Lenova\.nuget\packages\bootstrap\4.5.3\contentFiles\any\any\wwwroot\js\bootstrap.bundle.min.js"></script>

</body>

</html>